#!/bin/sh
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/glibmm2.4/libglibmm-2.4-1c2a_2.42.0-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dev_2.19-10ubuntu2.3_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/glibc/libc-dev-bin_2.19-10ubuntu2.3_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dbg_2.19-10ubuntu2.3_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.19-10ubuntu2.3_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/p/pcre3/libpcre3_8.35-3ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libs/libselinux/libselinux1_2.3-1build1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/glib2.0/libglib2.0-bin_2.42.1-1~ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/glib2.0/libglib2.0-0_2.42.1-1~ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxext/libxext6_1.3.2-1ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6_2.5.2-2ubuntu1.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxrender/libxrender1_0.9.8-1build0.14.10.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/c/cairo/libcairo2_1.13.0~20140204-0ubuntu1.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/c/cairo/libcairo-gobject2_1.13.0~20140204-0ubuntu1.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/c/cairo/libcairo-script-interpreter2_1.13.0~20140204-0ubuntu1.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/m/mesa/libgbm1_10.3.2-0ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/m/mesa/libegl1-mesa-drivers_10.3.2-0ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/m/mesa/libwayland-egl1-mesa_10.3.2-0ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/m/mesa/libegl1-mesa_10.3.2-0ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/m/mesa/libgl1-mesa-dri_10.3.2-0ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/m/mesa/libgl1-mesa-glx_10.3.2-0ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/m/mesa/libglapi-mesa_10.3.2-0ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libg/libglade2/libglade2-0_2.6.4-2_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/gtkmm2.4/libgtkmm-2.4-1c2a_2.24.4-1.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/h/harfbuzz/libharfbuzz-gobject0_0.9.35-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/p/pcre3/libpcrecpp0_8.35-3ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gtkglext/libgtkglext1_1.2.0-3.2fakesync1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gtkglextmm/libgtkglextmm-x11-1.2-0_1.2.0-6ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/p/po-debconf/po-debconf_1.0.16+nmu3_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/a/apparmor/dh-apparmor_2.8.98-0ubuntu2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/d/debhelper/debhelper_9.20140613ubuntu2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/gtk+2.0/gir1.2-gtk-2.0_2.24.25-0ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/p/pcre3/libpcre3-dev_8.35-3ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/z/zlib/zlib1g-dev_1.2.8.dfsg-1ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/glib2.0/libglib2.0-dev_2.42.1-1~ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/a/atk1.0/libatk1.0-dev_2.12.0-1ubuntu2_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libs/libsigc++-2.0/libsigc++-2.0-dev_2.2.11-4_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/glibmm2.4/libglibmm-2.4-dev_2.42.0-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/a/atkmm1.6/libatkmm-1.6-dev_2.22.7-2.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/e/expat/libexpat1-dev_2.1.0-6ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-dev_1.2.51-0ubuntu3_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6-dev_2.5.2-2ubuntu1.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/f/fontconfig/libfontconfig1-dev_2.11.1-0ubuntu3_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/xorg-sgml-doctools/xorg-sgml-doctools_1.11-1_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-core/x11proto-core-dev_7.0.26-1_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxau/libxau-dev_1.0.8-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxdmcp/libxdmcp-dev_1.1.1-1build1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-input/x11proto-input-dev_2.3.1-1_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-kb/x11proto-kb-dev_1.0.6-2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/xtrans/xtrans-dev_1.3.4-1_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libp/libpthread-stubs/libpthread-stubs0-dev_0.3-4_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb1-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libx11/libx11-dev_1.6.2-2ubuntu2_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-render/x11proto-render-dev_0.11.1-2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxrender/libxrender-dev_0.9.8-1build0.14.10.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libi/libice/libice-dev_1.0.9-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libs/libsm/libsm-dev_1.2.2-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/p/pixman/libpixman-1-dev_0.32.4-1ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-render0-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-shm0-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-xext/x11proto-xext-dev_7.3.0-1_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxext/libxext-dev_1.3.2-1ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/c/cairo/libcairo2-dev_1.13.0~20140204-0ubuntu1.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/c/cairomm/libcairomm-1.0-dev_1.10.0-1ubuntu3_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libd/libdrm/libdrm-dev_2.4.56-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/gdk-pixbuf/libgdk-pixbuf2.0-dev_2.30.8-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/xft/libxft-dev_2.3.2-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/h/harfbuzz/libharfbuzz-dev_0.9.35-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpango1.0-dev_1.36.6-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-xinerama/x11proto-xinerama-dev_1.2.1-2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxinerama/libxinerama-dev_1.1.3-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-fixes/x11proto-fixes-dev_5.0-2ubuntu2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxfixes/libxfixes-dev_5.0.1-2_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxi/libxi-dev_1.7.4-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-randr/x11proto-randr-dev_1.4.0+git20120101.is.really.1.4.0-0ubuntu1_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxrandr/libxrandr-dev_1.4.2-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcursor/libxcursor-dev_1.1.14-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-composite/x11proto-composite-dev_0.4.2-2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcomposite/libxcomposite-dev_0.4.4-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-damage/x11proto-damage-dev_1.2.1-2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxdamage/libxdamage-dev_1.1.4-2_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2-utils_2.9.1+dfsg1-4ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/gtk+2.0/libgtk2.0-dev_2.24.25-0ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2-dev_2.9.1+dfsg1-4ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libg/libglade2/libglade2-dev_2.6.4-2_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/universe/libg/libglademm2.4/libglademm-2.4-1c2a_2.6.7-4_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/p/pangomm/libpangomm-1.4-dev_2.34.0-1.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/g/gtkmm2.4/libgtkmm-2.4-dev_2.24.4-1.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/universe/libg/libglademm2.4/libglademm-2.4-dev_2.6.7-4_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/m/mesa/mesa-common-dev_10.3.2-0ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libx11/libx11-xcb-dev_1.6.2-2ubuntu2_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-dri3-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-randr0-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-shape0-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-xfixes0-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-sync-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-present-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxshmfence/libxshmfence-dev_1.1-3_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-dri2-0-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxcb/libxcb-glx0-dev_1.10-2ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-xf86vidmode/x11proto-xf86vidmode-dev_2.3.1-2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxxf86vm/libxxf86vm-dev_1.1.3-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-dri2/x11proto-dri2-dev_2.8-2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/x/x11proto-gl/x11proto-gl-dev_1.4.17-1_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/m/mesa/libgl1-mesa-dev_10.3.2-0ubuntu0.1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libg/libglu/libglu1-mesa-dev_9.0.0-2_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxt/libxt-dev_1.1.4-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxmu/libxmu-headers_1.1.2-1_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libxmu/libxmu-dev_1.1.2-1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/p/pangox-compat/libpangox-1.0-dev_0.0.2-4ubuntu1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gtkglext/libgtkglext1-dev_1.2.0-3.2fakesync1_amd64.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libs/libsys-hostname-long-perl/libsys-hostname-long-perl_1.4-3_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libm/libmail-sendmail-perl/libmail-sendmail-perl_0.79.16-1_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/main/libx/libx11/libx11-doc_1.6.2-2ubuntu2_all.deb
wget -c http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gtkglextmm/libgtkglextmm-x11-1.2-dev_1.2.0-6ubuntu1_amd64.deb
